import { AppBar } from "../components/AppBar";
import { Footer } from "../components/Footer";

export default function Policy() {
    return (
        <>
            <AppBar />
            <div className="px-48 pb-20 pt-36 bg-gradient-to-r from-green-300 via-blue-300 to-purple-300 min-h-screen flex items-center justify-center">
                <div className="bg-white p-10 rounded-xl shadow-2xl ">
                    <h1 className="text-3xl font-bold mb-6 text-gray-800 text-center">Privacy Policy</h1>
                    <p className="mb-4 text-gray-600">
                        This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                    </p>
                    <p className="mb-4 text-gray-600">
                        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                    </p>
                    <h2 className="text-2xl font-semibold mb-4 text-gray-800">Interpretation and Definitions</h2>
                    <h3 className="text-xl font-semibold mb-2 text-gray-800">Interpretation</h3>
                    <p className="mb-4 text-gray-600">
                        The words of which the initial letter is capitalized have meanings defined under the following conditions.
                    </p>
                    <p className="mb-4 text-gray-600">
                        The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                    </p>
                    <h3 className="text-xl font-semibold mb-2 text-gray-800">Definitions</h3>
                    <p className="mb-4 text-gray-600">For the purposes of this Privacy Policy:</p>
                    <ul className="list-disc list-inside mb-4 text-gray-600">
                        <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                        <li><strong>Company</strong> (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to harkirat.classx.co.in.</li>
                        <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                        <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                        <li><strong>Service</strong> refers to the Website.</li>
                        <li><strong>Country</strong> refers to: Uttar Pradesh, India</li>
                        <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                        <li><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
                        <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                        <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                    </ul>
                    <h2 className="text-2xl font-semibold mb-4 text-gray-800">Collecting and Using Your Personal Data</h2>
                    <h3 className="text-xl font-semibold mb-2 text-gray-800">Types of Data Collected</h3>
                    <h4 className="text-lg font-semibold mb-2 text-gray-800">Personal Data</h4>
                    <p className="mb-4 text-gray-600">
                        While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                    </p>
                    <ul className="list-disc list-inside mb-4 text-gray-600">
                        <li>Email address</li>
                        <li>First name and last name</li>
                        <li>Phone number</li>
                        <li>Usage Data</li>
                    </ul>
                    <h4 className="text-lg font-semibold mb-2 text-gray-800">Usage Data</h4>
                    <p className="mb-4 text-gray-600">
                        Usage Data is collected automatically when using the Service.
                    </p>
                    <p className="mb-4 text-gray-600">
                        Usage Data may include information such as Your Device’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                    </p>
                    <p className="mb-4 text-gray-600">
                        When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
                    </p>
                    <p className="mb-4 text-gray-600">
                        We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
                    </p>
                    <h4 className="text-lg font-semibold mb-2 text-gray-800">Tracking Technologies and Cookies</h4>
                    <p className="mb-4 text-gray-600">
                        We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
                    </p>
                    <p className="mb-4 text-gray-600">
                        You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.
                    </p>
                    <p className="mb-4 text-gray-600">
                        Cookies can be “Persistent” or “Session” Cookies. Persistent Cookies remain on your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close your web browser.
                    </p>
                    <p className="mb-4 text-gray-600">
                        We use both session and persistent Cookies for the purposes set out below:
                    </p>
                    <ul className="list-disc list-inside mb-4 text-gray-600">
                        <li><strong>Necessary / Essential Cookies</strong><br />Type: Session Cookies<br />Administered by: Us<br />Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</li>
                        <li><strong>Cookies Policy / Notice Acceptance Cookies</strong><br />Type: Persistent Cookies<br />Administered by: Us<br />Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</li>
                        <li><strong>Functionality Cookies</strong><br />Type: Persistent Cookies<br />Administered by: Us<br />Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</li>
                    </ul>
                    <p className="mb-4 text-gray-600">
                        For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy.
                    </p>
                    <h3 className="text-xl font-semibold mb-2 text-gray-800">Use of Your Personal Data</h3>
                    <p className="mb-4 text-gray-600">
                        The Company may use Personal Data for the following purposes:
                    </p>
                    <ul className="list-disc list-inside mb-4 text-gray-600">
                        <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
                        <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
                        <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                        <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application’s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
                    </ul>
                    <h3 className="text-lg font-semibold mb-2">Retention of Your Personal Data</h3>
                    <p className="mb-4">
                        The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                    </p>
                    <p className="mb-4">
                        The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
                    </p>
                    <h3 className="text-lg font-semibold mb-2">Transfer of Your Personal Data</h3>
                    <p className="mb-4">
                        Your information, including Personal Data, is processed at the Company’s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
                    </p>
                    <p className="mb-4">
                        Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
                    </p>
                    <p className="mb-4">
                        The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
                    </p>
                    <h3 className="text-lg font-semibold mb-2">Disclosure of Your Personal Data</h3>
                    <p className="mb-4">
                        <strong>Business Transactions:</strong> If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
                    </p>
                    <p className="mb-4">
                        <strong>Law enforcement:</strong> Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
                    </p>
                    <p className="mb-4">
                        <strong>Other legal requirements:</strong> The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
                    </p>
                    <ul className="list-disc list-inside mb-4">
                        <li>Comply with a legal obligation</li>
                        <li>Protect and defend the rights or property of the Company</li>
                        <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                        <li>Protect the personal safety of Users of the Service or the public</li>
                        <li>Protect against legal liability</li>
                    </ul>
                    <h3 className="text-lg font-semibold mb-2">Security of Your Personal Data</h3>
                    <p className="mb-4">
                        The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                    </p>
                    <h3 className="text-lg font-semibold mb-2">Children’s Privacy</h3>
                    <p className="mb-4">
                        Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
                    </p>
                    <p className="mb-4">
                        We also may limit how We collect, use, and store some of the information of Users between 13 and 18 years old. In some cases, this means We will be unable to provide certain functionality of the Service to these users.
                    </p>
                    <p className="mb-4">
                        If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent’s consent before We collect and use that information.
                    </p>
                    <h3 className="text-lg font-semibold mb-2">Links to Other Websites</h3>
                    <p className="mb-4">
                        Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party’s site. We strongly advise You to review the Privacy Policy of every site You visit.
                    </p>
                    <p className="mb-4">
                        We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                    </p>
                    </div>
                </div>
<Footer />
</>
);
}

